### Fügt einen neuen User hinzu
POST http://localhost:3000/addUser HTTP/1.1
Content-Type: application/json

{
    "name": "user1",
    "email": "user1@test.com",
    "password": "User1User1"
}


### Zeigt alle User an
GET http://localhost:3000/users HTTP/1.1


### Löscht den User mit der ID und alle seine Einträge im history table
DELETE http://localhost:3000/deleteUser/10 HTTP/1.1


### Login mit Benutzername oder E-Mail und Passwort
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "usernameOrEmail": "user123",
    "password": "DieAppistToll"
}


### Registrierung eines neuen Benutzers
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "name": "user123",
    "email": "user123@example.com",
    "password": "DieAppistToll"
}


### Win wird bei bestimmten User um 1 erhöht
POST  http://localhost:3000/addWin/2 HTTP/1.1
Content-Type: application/json


### Lose wird bei bestimmten User um 1 erhöht
POST  http://localhost:3000/addLoss/2 HTTP/1.1
Content-Type: application/json


### Erhöht roundsWon bei bestimmten User um 1
POST  http://localhost:3000/addRoundWin/2 HTTP/1.1
Content-Type: application/json


### Erhöht roundsLost bei bestimmten User um 1
POST  http://localhost:3000/addRoundLoss/2 HTTP/1.1
Content-Type: application/json


### Erhöht flawlessVictories bei bestimmten User um 1
POST  http://localhost:3000/addFlawlessVictory/2 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/deleteUserStats/3 HTTP/1.1
Content-Type: application/json

